# your informations
author:
  name: Hafidz Nasruddin
  description: System administrator
  picture: /assets/images/avatar.png

# site description
description: Thoughts and writings by Hafidz Nasruddin .

# site url
url: http://hafidz.me

# site title
title: Hafidz Nasruddin

# site version
version: 1.0.0

# number of posts per page
paginate: 10

# your github username
github_username: apisznasdin

# set true to include or false to exclude share option
share:
  twitter: true
  facebook: false
  google_plus: true
  linkedin: true
  disqus: true

# if share.facebook is true, provide your facebook app id
facebook_app_id: 730635297031262

# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
disqus_username: hafidzme
disqus_api_key: ob0FZe2fQrcJotg5aEETqfS3RiFylshDbRZ7FUjFQOPPVzEv2lHFeWGRRxUwMbNB 
disqus_recent_comments_to_display: 5

# google analytics ID
google_analytics_id: UA-39105618-3

markdown: kramdown
highlighter: pygments
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]
